# Basic dependabot.yml file for npm

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the root directory
    directory: "/"
    # Check for updates daily (weekly is default)
    schedule:
      interval: "daily"
    # Add assignees
    # assignees:
    #  - "your-github-username"
    # Add reviewers
    # reviewers:
    #  - "your-github-username"
    # Add labels
    # labels:
    #  - "dependencies"